const app=document.querySelector('#app'),header=document.querySelector('.header'),home=document.querySelector('#home-template').content;
const quick=[
['Your habits','When I have an important decision to make, what do I do first?',['Ask someone I trust','Research everything','Go with my first instinct','Wait until I have to decide']],
['Your habits','What is the most likely reason I would be late?',['I lost track of time','I changed outfits too many times','I was helping someone else','I left late on purpose']],
['Your taste','Which gift would mean the most to me?',['Something useful','Something handmade','An experience together','A surprise I did not ask for']],
['Your social side','At a busy event, where would you probably find me?',['Talking to one person','Meeting everyone','Near the food','Looking for a quiet corner']],
['Your standards','What makes me lose interest in someone fastest?',['They are inconsistent','They are rude to people','They take themselves too seriously','They never say what they mean']],
['Your routines','What do I do when I cannot sleep?',['Watch something familiar','Scroll longer than I should','Make a plan for tomorrow','Listen to music']],
['Your taste','Which choice am I most likely to defend even when people disagree?',['My music taste','My food order','My opinion about a movie','My way of doing things']],
['Your past','What was I probably like as a child?',['Quiet but observant','Always asking questions','Competitive about everything','The person making everyone laugh']],
['Your priorities','If I had a completely free day, what would I value most?',['No schedule at all','Time with one close person','Trying somewhere new','Finishing something I started']],
['The hard one','What is something people often get wrong about me?',['They think I am more confident than I am','They think I do not care','They think I am always serious','They think I am easy to read']]
].map(([category,text,options])=>({category,text,options}));
let state={name:'',mode:'quick',questions:[],answers:[],index:0};
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async(path,method='GET',body)=>{const r=await fetch('/api'+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw Error(d.error||'Something went wrong.');return d};
function view(html,small=false){header.style.display=small?'none':'flex';app.innerHTML=html;window.scrollTo(0,0)}
function homeView(){app.replaceChildren(home.cloneNode(true));header.style.display='flex';window.scrollTo(0,0)}
function createView(){view(`<section class="page"><button class="back" data-back>← Home</button><div class="panel"><p class="eyebrow">START YOUR QUIZ</p><h1>What should we call you?</h1><p class="help">This is shown to people taking your quiz.</p><label class="field-label">Your name or nickname</label><input class="text-input" id="name" maxlength="30" placeholder="e.g. Selman"><button class="primary wide" id="name-next">Continue <span>→</span></button></div></section>`);document.querySelector('#name-next').onclick=()=>{const n=document.querySelector('#name').value.trim();if(!n)return document.querySelector('#name').focus();state.name=n;modeView()}}
function modeView(){view(`<section class="page"><button class="back" data-back>← Back</button><div class="panel"><p class="eyebrow">${esc(state.name)}</p><h1>How do you want to make your quiz?</h1><div class="mode-list"><label class="mode"><input type="radio" name="mode" value="quick" checked><span>✦</span><span><b>Quick Start</b><small>Use 10 ready-made questions.</small></span><i class="dot"></i></label><label class="mode"><input type="radio" name="mode" value="mix"><span>✦＋</span><span><b>Mix</b><small>Start with 7 questions and add your own.</small></span><i class="dot"></i></label><label class="mode"><input type="radio" name="mode" value="custom"><span>+</span><span><b>Custom</b><small>Write every question yourself.</small></span><i class="dot"></i></label></div><button class="primary wide" id="mode-next">Continue <span>→</span></button></div></section>`);document.querySelector('#mode-next').onclick=()=>{state.mode=document.querySelector('input[name=mode]:checked').value;state.questions=state.mode==='quick'?structuredClone(quick):state.mode==='mix'?structuredClone(quick.slice(0,7)):[blank(),blank(),blank()];state.mode==='quick'?creatorQuestion():builderView()}}
const blank=()=>({category:'Your question',text:'',options:['','','','']});
function builderView(){view(`<section class="page"><button class="back" data-back>← Back</button><div class="builder-head"><div><p class="eyebrow">${state.mode==='mix'?'ADD YOUR QUESTIONS':'CUSTOM QUESTIONS'}</p><h1>Set the right answer first.</h1></div><button class="secondary" id="add-question">+ Add question</button></div><p class="help">Each question needs four answers. Choose the correct one.</p><div id="cards"></div><div class="builder-actions"><button class="secondary" data-back>Back</button><button class="primary" id="builder-next">Answer my quiz <span>→</span></button></div></section>`);renderCards();document.querySelector('#add-question').onclick=()=>{state.questions.push(blank());renderCards()};document.querySelector('#builder-next').onclick=()=>{const cards=[...document.querySelectorAll('.question-card')];let valid=true;state.questions.forEach((q,i)=>{q.text=cards[i].querySelector('[data-text]').value.trim();q.options=[...cards[i].querySelectorAll('[data-option]')].map(x=>x.value.trim());q.answer=Number(cards[i].querySelector('[data-answer]:checked')?.value);if(!q.text||q.options.some(x=>!x)||Number.isNaN(q.answer))valid=false});if(!valid)return alert('Complete every question, answer, and correct-answer choice.');state.index=0;state.answers=[];creatorQuestion()}}
function renderCards(){document.querySelector('#cards').innerHTML=state.questions.map((q,i)=>`<article class="question-card"><div class="question-card-top"><h2>Question ${i+1}</h2>${state.mode==='custom'&&state.questions.length>1?`<button class="remove" data-remove="${i}">Remove</button>`:''}</div><label class="field-label">Question</label><input class="text-input" data-text value="${esc(q.text)}" placeholder="Write a question"><label class="field-label">Answers — select the correct one</label>${q.options.map((o,j)=>`<label class="option-row"><input type="radio" name="correct-${i}" data-answer value="${j}" ${j===0?'checked':''}><input class="text-input" data-option value="${esc(o)}" placeholder="Answer ${j+1}"></label>`).join('')}</article>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{state.questions.splice(Number(b.dataset.remove),1);renderCards()})}
function creatorQuestion(){const q=state.questions[state.index];view(`<section class="page question"><div class="question-top"><span>${state.index+1} / ${state.questions.length}</span><div class="bar"><i style="width:${(state.index+1)/state.questions.length*100}%"></i></div></div><p class="eyebrow">${esc(q.category||'YOUR QUIZ')}</p><h1>${esc(q.text)}</h1><p class="help">Choose your answer. This is the answer your friends will try to guess.</p><div class="answers">${q.options.map((o,i)=>`<button class="answer" data-answer="${i}"><span class="letter">${'ABCD'[i]}</span>${esc(o)}</button>`).join('')}</div></section>`,true);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{state.answers[state.index]=Number(b.dataset.answer);state.index++;state.index<state.questions.length?creatorQuestion():saveQuiz()})}
async function saveQuiz(){view('<p class="loading">Saving your quiz…</p>',true);try{const d=await api('/quizzes','POST',{creatorName:state.name,questions:state.questions,answers:state.answers});history.pushState({},'',`/?manage=${d.id}&key=${d.creatorKey}`);shareView(d)}catch(e){view(`<section class="page"><p class="error">${esc(e.message)}</p></section>`)} }
function shareView(q){const link=`${location.origin}/?quiz=${q.id}`,manage=`${location.origin}/?manage=${q.id}&key=${q.creatorKey}`;view(`<section class="page"><div class="panel"><p class="eyebrow">YOUR QUIZ IS READY</p><h1>Send this to people who claim they know you.</h1><p class="help">Their answers will be scored against yours.</p><div class="link-box"><code>${esc(link)}</code><button data-copy="${esc(link)}">Copy</button></div><button class="secondary" data-copy="${esc(manage)}">Copy creator results link</button><p class="small">Keep the creator results link private. It lets you view every response. The other link is the one to share.</p></div></section>`);copyButtons()}
function copyButtons(){document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=async()=>{await navigator.clipboard.writeText(b.dataset.copy);b.textContent='Copied'})}
async function friendView(id){view('<p class="loading">Loading quiz…</p>',true);try{const q=await api(`/quizzes/${id}`);let i=0,answers=[];const step=()=>{const x=q.questions[i];view(`<section class="page question"><div class="question-top"><span>${i+1} / ${q.questions.length}</span><div class="bar"><i style="width:${(i+1)/q.questions.length*100}%"></i></div></div><p class="eyebrow">${esc(q.creatorName.toUpperCase())}'S QUIZ</p><h1>${esc(x.text)}</h1><p class="help">What do you think they chose?</p><div class="answers">${x.options.map((o,j)=>`<button class="answer" data-answer="${j}"><span class="letter">${'ABCD'[j]}</span>${esc(o)}</button>`).join('')}</div></section>`,true);document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{answers[i]=Number(b.dataset.answer);i++;i<q.questions.length?step():askFriend()})};const askFriend=()=>view(`<section class="page"><div class="panel"><p class="eyebrow">ONE MORE THING</p><h1>What should we call you?</h1><input class="text-input" id="friend-name" maxlength="30" placeholder="Your name or nickname"><button class="primary wide" id="submit-response">See my result <span>→</span></button></div></section>`,true);document.addEventListener('click',async e=>{if(e.target.id==='submit-response'){const n=document.querySelector('#friend-name').value.trim();if(!n)return;view('<p class="loading">Calculating…</p>',true);const r=await api(`/quizzes/${id}/responses`,'POST',{respondentName:n,answers});resultView(q,r)}},{once:false});step()}catch(e){view(`<section class="page"><p class="error">${esc(e.message)}</p></section>`)} }
function resultView(q,r){view(`<section class="page"><div class="panel result-card"><p class="eyebrow">${esc(r.respondentName.toUpperCase())}'S RESULT</p><div class="score">${r.score}/${q.questions.length}</div><p class="match">${Math.round(r.score/q.questions.length*100)}% match</p><div class="breakdown">${q.questions.map((x,i)=>`<article><span class="${r.answers[i]===r.correctAnswers[i]?'ok':'no'}">${r.answers[i]===r.correctAnswers[i]?'✓':'×'}</span><div><strong>${esc(x.text)}</strong><small>Their answer: ${esc(x.options[r.correctAnswers[i]])}</small></div></article>`).join('')}</div></div></section>`,true)}
async function manageView(id,key){view('<p class="loading">Loading results…</p>',true);try{const q=await api(`/quizzes/${id}/results?key=${encodeURIComponent(key)}`);view(`<section class="page"><div class="panel"><p class="eyebrow">CREATOR RESULTS</p><h1>${esc(q.creatorName)}’s MindMatch</h1>${q.responses.length?q.responses.map(r=>`<article class="question-card"><b>${esc(r.respondentName)}</b><p class="help">${r.score} / ${q.questionCount} correct · ${new Date(r.createdAt).toLocaleString()}</p></article>`).join(''):'<p class="empty">No one has taken this quiz yet.</p>'}</div></section>`,true)}catch(e){view(`<section class="page"><p class="error">${esc(e.message)}</p></section>`)} }
document.addEventListener('click',e=>{if(e.target.closest('[data-action=create]')||e.target.id==='home-create')createView();if(e.target.closest('[data-back]'))state.mode==='quick'||!state.questions.length?homeView():modeView()});
const p=new URLSearchParams(location.search);p.has('quiz')?friendView(p.get('quiz')):p.has('manage')?manageView(p.get('manage'),p.get('key')):homeView();
